### ISSUE TITLE
Offer a form or other lower barrier way to sign?

### ISSUE THREAD

**Issue by hannahhoward** [drop-ice/dear-github-2.0#190]
Thank you so much for the efforts!!!

I dunno if the motivation for using PR's is to insure that people know their way around open source, but it seems like a high barrier to entry for supporters, especially folks in tech who may not be developers but still play important roles in OSS projects.

I wonder about offering a form, petition, or some other simple way to signal support.

**Comment by Qix-** [comment]
Problem is identify verification. The benefit of using PRs is that we can validate the line being added belongs to the identity of the person adding it.

**Comment by drop-ice** [comment]
Thanks for suggesting this @hannahhoward !

We’d like to keep most of the signing activity on GitHub itself (that makes this repository more likely to “trend” in various parts of the GitHub.com user interface), but there are ways to make this more accessible.

For now, we’d like to ask people who would like to sign but are not comfortable making a pull request to please [file an issue](https://github.com/drop-ice/dear-github-2.0/issues/new/choose) asking someone to open one on your behalf. (We’ve added an issue template to make this straightforward.)

We’ll also edit #16 to include these instructions. Thank you!

**Comment by ctsstc** [comment]
Seems like a perfect time for a simple bot or new~ish github actions (add something like `/sign` that people can leave as a comment and the bot auto-ads them, thus they have to be logged in to type `/sign` in the thread, but having your own github signed PR is valuable too rather than by proxy.

**Comment by murb** [comment]
Maybe you could link directly to https://github.com/drop-ice/dear-github-2.0/edit/master/README.md, which offers a reasonably easy flow

**Comment by Qix-** [comment]
> that makes this repository more likely to “trend”

Would Github even allow that? Did the dear-github (v1) trend (e.g. show up in the right-hand side under trending)?
