### ISSUE TITLE
Alternative suggestion

### ISSUE THREAD

**Issue by markrendle** [drop-ice/dear-github-2.0#311]
Some thoughts:

1. It is highly unlikely that GitHub are going to deny service to ICE out of all the organizations they do business with, not least because it is straying into dangerous precedent territory.
2. Even if they did, there are plenty of alternatives to GitHub, and (ironically) most of them are open source: Gitlab, BitBucket, GOGS, Gitbucket are all open source with no control over who uses them.
3. From looking at their website, it's clear that ICE use lots of open source software, including (but not limited to) Apache, Drupal (and thus PHP), jQuery and a variety of plug-ins, Bootstrap, MediaElement and Respond.js.
4. That's just what can be determined from browser dev tools. ICE are certainly benefiting from a whole range of open source technologies, including Linux, Git itself, NPM (and Node.js), and who knows what else? In fact, they are almost certainly using things that have been contributed to by some of the signatories to this letter.
5. As open source products, there is nothing the maintainers of these projects can do to prevent ICE from using them. Yet they are, possibly even moreso than GitHub, enabling ICE.
6. The only distinction is that GitHub are making money from ICE, and therefore, indirectly, from their activities. And a part of that money - ICE's money - goes into whatever pot it is that GitHub use to keep the lights on for all the open source projects hosted here.

The suggestion.

Instead of demanding that GitHub cease trading with ICE, which is fraught with political and ethical problems, why not ask that they donate the profits they get from ICE to charities that help and support immigrants, such as the ACLU, RAICES, or any on [this list from Cornell Law School](https://www.lawschool.cornell.edu/MigrationandHumanRightsProgram/Organizations-seeking-non-lawyer-and-lawyer-volunteers.cfm). This is a more realistic outcome to ask for, and it will actually do some good, in a way that cutting ICE off from the platform will not. It would also be a PR win for GitHub.

This could be applied more widely to whatever companies are doing business with ICE. And maybe the open source projects that ICE are using could ask their users to donate to these causes as well.

**Comment by drop-ice** [comment]
We cannot offset human lives with money. There is no donation that can offset the harm that ICE is perpetuating with the help of our labor.

https://twitter.com/githubbers/status/1182017616740663296
