### ISSUE TITLE
Add my signature

### ISSUE THREAD

**Issue by jlanday** [drop-ice/dear-github-2.0#395]
Hi, I’d like to sign this letter in support of ending GitHub’s business with ICE. Please add my name, GitHub username, and affiliations as shown below.

**Name: Justin Landay** 
**Affiliations (optional): Data Scientist, Riot Games. Editor, The Gradient** 

<!--
(Examples of affiliations are organizations you work for or with, projects you contribute to, and/or anything else that feels appropriate for you.)
--!>

**Comment by remopong** [comment]
Please also add me

Name : Benard Rémi
Affiliation : Student in electronics
Username everywhere : Remopong

**Comment by lpil** [comment]
If you open a pull request adding your signature it can get merged in :)

**Comment by drop-ice** [comment]
Added Justin!

**Comment by drop-ice** [comment]
And Benard!
