### ISSUE TITLE
Note

### ISSUE THREAD

**Issue by cloudrex** [drop-ice/dear-github-2.0#429]
Even if they do drop the ICE contract, it's not really going to affect what's going on--in other words there's really no point.

Anyone care to comment on this?

**Comment by lpil** [comment]
They've had several members of staff leave over this issue, and presumably similar is happening for customers. It's hard to say the impact this has though.

**Comment by mr21** [comment]
@cloudrex with that mindset you can't really change anything... you are promoting Immobilism.

Why should i recycle my garbage? it will not impact the climate change...
Why should i vote? i'm a so tiny percentage of the country.

**Comment by cloudrex** [comment]
I think you're mistaken. There are just many other different, perhaps more efficient ways. My issue is how does this really affect the problem in hand?

**Comment by cloudrex** [comment]
Additionally, the CEO (Nat) has already expressed his disagreement with the Trump's administration policies, and he also stated that they're going to proceed with the contract. So in other words this entire thing is likely to have no tangible outcome.

**Comment by mr21** [comment]
See it like we (the people who signed the repo) are showing our disagreement too, just like Nat.

**Comment by cloudrex** [comment]
@mr21 I'm sorry I have the feeling that you're taking this personally. This discussion is not about me. Please re-read my post to see what I'm willing to discuss.

**Comment by ljharb** [comment]
@cloudrex the point *is* to express disagreement. While change can be hoped for, change (nor any tangible outcome) is not required for this effort to be meaningful.
