### ISSUE TITLE
Add my signature

### ISSUE THREAD

**Issue by AndreiJirohHaliliDev2006** [drop-ice/dear-github-2.0#441]
Hi, I’d like to sign this letter in support of ending GitHub’s business with ICE. Please add my name, GitHub username, and affiliations as shown below.

**Name: Andrei Jiroh** 
**Affiliations (optional): Project Maintainer of the Pins team's projects (https://github.com/MadeByThePinsHub)** 

<!--
(Examples of affiliations are organizations you work for or with, projects you contribute to, and/or anything else that feels appropriate for you.)
--!>

**Comment by lpil** [comment]
If you open a pull request adding your signature it can get merged in :)

**Comment by drop-ice** [comment]
Done! Thank you!
