### ISSUE TITLE
When to merge? 

### ISSUE THREAD

**Issue by mlvidart** [drop-ice/dear-github-2.0#469]
Hey! 

I'm newish to GitHub. I forked the repo, created a PR, but who merges? Am I in charge once it's approved? If so, who approves, and who should I add as a reviewer? It would be helpful to have some guidance on that.

**Comment by drop-ice** [comment]
Welcome! We are doing the merging as owners of the repo, but working on a bit of a backlog. Should be in soon!

**Comment by drop-ice** [comment]
You are all merged in! Thank for your patience!
