### ISSUE TITLE
Letter forgot to mention all the killers and rapists ICE removes form USA and keeping America SAFE

### ISSUE THREAD

**Issue by trump2040** [drop-ice/dear-github-2.0#498]

**Comment by mr21** [comment]
What are you talking about? the killers and rapists are well installed in the WH, the ICE has no right to remove them...

**Comment by bobolobo** [comment]
...and yet not.  Watch the news you will see it of course depending on what news you watch. You watch the left-media-we-don't-print-all-the-news... you know, like Bloomberg and the rest...  

Never thought I would see the day when protecting our borders was a bad thing.  It's OK for every other country to do so though.

**Comment by mr21** [comment]
I just come back from Twitter, and i saw a child die in your "border protection".
If this child was a threat to the USA community, then you are not that strong at all...

**Comment by bobolobo** [comment]
How many more died coming here enmasse in an organized orchestrated train of thousands, passing through other nations by the way.

**Comment by mr21** [comment]
You're doing some whataboutism? or it's me i don't see the link between your messages?

In Europe our lives are a magnitude above your confort. I can afford a MIT like school while being saved from Cancer, without having any penny... You can't compare the usa with Western Europe. Sorry.
We saw you as a developing country.

**Comment by mr21** [comment]
And those immigrate people who came into USA, are doing the jobs that you don't want to do.
There are cities emptied by the ICE, with now white people complaining about how hard is to have to work...

So if you want to slowdown your economy just for racism... i don't have any argument.
