### ISSUE TITLE
Are you open to people signing it the opposite way and saying you are wrong?

### ISSUE THREAD

**Issue by NathanaelA** [drop-ice/dear-github-2.0#58]
As an open source developer, I think you are 100% wrong.  :grinning:    However, it is probably not in the way you see it.   I don't support the ICE tactics -- the issue is the very slippery slope this open letter creates.    

**Either it is open source, or it is not.**    

If it is open source, then **anyone** can use it.   If it isn't; then where does it stop.

Say I don't want Github (or insert company/project) being used by Planned Parenthood?    Or maybe the Democratic/Republican/Labor Party?   Or maybe Nestle or Johnson and Johnson, what about Chick-fila or McDonalds, Walmart, Target?    Where does this stop?

If things like this actually gain wings (and works), then you create the turning point to erode any remaining community cohesiveness as people with other pet causes see this as a way to maybe force their pet cause and it is no longer open source.      And then we set the stage to have a fractured community of packages all restricting use if you are working for "agency" that you are against.  

**Either it is open source, or it is not.**

**Comment by NoraCodes** [comment]
GitHub isn't open source and never has been, though.

**Comment by joenash** [comment]
If “open” as an ultimate good allows us to put thousands of kids in cages, maybe we should inspect those values.

**Comment by DEGoodmanWilson** [comment]
https://dev.to/degoodmanwilson/open-source-is-broken-g60

**Comment by NathanaelA** [comment]
@NoraCodes / @joenash  - Git is open source, Github is used by open source.   
Point remains that if you start putting arbitrary limits on the code; others will put arbitrary limits on it.   Do you really want to open that can of worms?     

Please do NOT get me wrong, I am NOT in any fashion defending ICE.     My issue with this ISN'T you restricting ICE, it is you restricting ANYONE.   Had this letter been to restrict Nestle because of their negative environmental impact; I would have posted the exact same thing.    Either it is Open source or it isn't.

Example:   If you like planned parenthood and I decided I didn't.  Would you be happy if say I could convince mysql, postgresql, and mariadb to ban all planned parenthood use of their software?     Do you see the slippery slope this creates?   

I am all for putting pressure on ICE to stop the nasty behavior; the issue I believe is this is the WRONG way to do it...

---

@DEGoodmanWilson - I read that actually last night when I saw your thread on leaving github; it is very well written and brings up very interesting points I have been aware of for a while.  And as such, I created a org to deal with some of them in the eco-system I am very active in about 6 months ago.   If it goes well in the eco-system I am in, I might expand it to other simular eco-systems...  :-D

Unfortunately the article doesn't dissuade me into thinking this specific type of action is the wrong way to proceed forward and just shoots us all in the foot.

**Comment by cmcaine** [comment]
> Example: If you like planned parenthood and I decided I didn't. Would you be happy if say I could convince mysql, postgresql, and mariadb to ban all planned parenthood use of their software? Do you see the slippery slope this creates?

The only way that would work is if you persuaded the maintainers to fork it under a new license. Good luck with that. But, sure, if you persuade some developers to relicense their code under a bigoted license, then I guess you get to keep it.

Depending on the particular bigotry you might get to explore the sharp side of anti-discrimination laws in the EU and elsewhere.

> I am all for putting pressure on ICE to stop the nasty behavior; the issue I believe is this is the WRONG way to do it...

What specific action do you condone for putting pressure on ICE? If it doesn't extend to asking a private company to stop selling services to ICE I suspect you may not oppose ICE as much as you'd like to think.

**Comment by drop-ice** [comment]
> Are you open to people signing it the opposite way and saying you are wrong?

No.

This letter addresses a specific decision by the company GitHub to do business with an organization that violates human rights. If you'd like to address other issues or if you disagree with the stance put forward, please write create your own communication. Thanks!
