### ISSUE TITLE
Add my signature

### ISSUE THREAD

**Issue by iddan** [drop-ice/dear-github-2.0#688]
Hi, I’d like to sign this letter in support of ending GitHub’s business with ICE. Please add my name, GitHub username, and affiliations as shown below.

**Name:**  Iddan Aaronsohn
**Affiliations (optional):** Open Source Maintainer

**Comment by cluzier** [comment]
Fork the repository, add your name to the README file and submit a PR

**Comment by drop-ice** [comment]
closed by #707
