### ISSUE TITLE
by not including ICE on github, we limit transparency of government

### ISSUE THREAD

**Issue by castrated** [drop-ice/dear-github-2.0#781]
please consider that while the government will always be secretive, limitation of transparent federal contributions on an open-source platform is inherently evil in software ethics.

**Comment by ljharb** [comment]
This is about an enterprise contract GitHub has with ice for non-public code; it does not affect transparency of government whatsoever.

**Comment by castrated** [comment]
i don't care

**Comment by ljharb** [comment]
Yeah most people that don’t care go trolling  on GitHub

**Comment by drop-ice** [comment]
What @ljharb said.
