### ISSUE TITLE
Request to have Repo linked to GitHub Feedback Repo: (+Signature Request)

### ISSUE THREAD

**Issue by Nulled-Out** [drop-ice/dear-github-2.0#995]
Hi, I’d like to sign this letter in support of ending GitHub’s business with ICE. Please add my name, GitHub username, and affiliations as shown below.

**Name: Dasein** 
**Affiliations (optional): f-OSS Archives** 

<!--
 A big fan of & believer in the Free & Open-Source Ecosystem ✊🏽 
--!>

**Comment by Daasin** [comment]
Also would it be possible to have your pinned issue referenced on GitHub Feedback Discussions? 
 
https://github.com/github/feedback/discussions/12042 - Similarly to this kind of approach? Although the pull request/issue creation can be a barrier, was hesitant myself before I knew how to use GitHub 😅 
 
(Some would say I still don't haha :)
